export const COLOR_OPTIONS = [
    { name: "Black", code: "#000000" },
    { name: "White", code: "#FFFFFF" },
    { name: "Red", code: "#FF0000" },
    { name: "Maroon", code: "#800000" },
    { name: "Pink", code: "#FF69B4" },
    { name: "Purple", code: "#800080" },
    { name: "Blue", code: "#0000FF" },
    { name: "Navy Blue", code: "#000080" },
    { name: "Sandal", code: "#C2B280" },
    { name: "Sky Blue", code: "#87CEEB" },
    { name: "Green", code: "#008000" },
    { name: "Baby Pink", code: "#F4C2C2" },                                      { name: "Peach", code: "#FFDAB9" },
{ name: "Rose Pink", code: "#FF66CC" },
{ name: "Rani Pink", code: "#E0115F" },
{ name: "Magenta", code: "#FF00FF" },
{ name: "Wine", code: "#722F37" },
{ name: "Burgundy", code: "#800020" },
{ name: "Lavender", code: "#E6E6FA" },
{ name: "Lilac", code: "#C8A2C8" },
{ name: "Violet", code: "#8F00FF" },
{ name: "Teal", code: "#008080" },
{ name: "Turquoise", code: "#40E0D0" },
{ name: "Mint Green", code: "#98FF98" },
{ name: "Pista Green", code: "#93C572" },
{ name: "Parrot Green", code: "#54B948" },
{ name: "Emerald Green", code: "#50C878" },
{ name: "Sea Green", code: "#2E8B57" },
{ name: "Royal Blue", code: "#4169E1" },
{ name: "Powder Blue", code: "#B0E0E6" },
{ name: "Grey", code: "#808080" },
{ name: "Charcoal Grey", code: "#36454F" },
{ name: "Ivory", code: "#FFFFF0" },
{ name: "Off White", code: "#FAF9F6" },
{ name: "Nude", code: "#E3BC9A" },
{ name: "Tan", code: "#D2B48C" },
{ name: "Chocolate Brown", code: "#7B3F00" },
{ name: "Rust", code: "#B7410E" },
{ name: "Coral", code: "#FF7F50" },
{ name: "Copper", code: "#B87333" },
    { name: "Bottle Green", code: "#006A4E" },
    { name: "Olive Green", code: "#556B2F" },
    { name: "Yellow", code: "#FFD700" },
    { name: "Mustard", code: "#FFDB58" },
    { name: "Orange", code: "#FFA500" },
    { name: "Brown", code: "#8B4513" },
    { name: "Beige", code: "#F5F5DC" },
    { name: "Cream", code: "#FFFDD0" },
    { name: "Gold", code: "#D4AF37" },
    { name: "Silver", code: "#C0C0C0" },
];